export default {
  CHAT_CLEAR_DATA: "CHAT_CLEAR_DATA",
  CHAT_SCROLL_TO_BOTTOM_TOGGLE: "CHAT_SCROLL_TO_BOTTOM_TOGGLE",

  CHAT_CREATE_START: "CHAT_CREATE_START",
  CHAT_CREATE_SUCCESS: "CHAT_CREATE_SUCCESS",
  CHAT_CREATE_ERROR: "CHAT_CREATE_ERROR",

  CHAT_GET_START: "CHAT_GET_START",
  CHAT_GET_SUCCESS: "CHAT_GET_SUCCESS",
  CHAT_GET_ERROR: "CHAT_GET_ERROR",

  CHAT_UPDATE_START: "CHAT_UPDATE_START",
  CHAT_UPDATE_SUCCESS: "CHAT_UPDATE_SUCCESS",
  CHAT_UPDATE_ERROR: "CHAT_UPDATE_ERROR",

  CHAT_DESTROY_START: "CHAT_DESTROY_START",
  CHAT_DESTROY_SUCCESS: "CHAT_DESTROY_SUCCESS",
  CHAT_DESTROY_ERROR: "CHAT_DESTROY_ERROR",

  REQUEST_DESTROY_START: "REQUEST_DESTROY_START",
  REQUEST_DESTROY_SUCCESS: "REQUEST_DESTROY_SUCCESS",
  REQUEST_DESTROY_ERROR: "REQUEST_DESTROY_ERROR",

  TARGET_CONVERSATION_START: "TARGET_CONVERSATION_START",
  TARGET_CONVERSATION: "TARGET_CONVERSATION",
  CLICK_TARGET: "CLICK_TARGET",

  CHANGE_CONVERSATION: "CHANGE_CONVERSATION",

  SOCKET_SENT_MESSAGE: "SOCKET_SENT_MESSAGE",
  CHAT_CREATE_GROUP_START: "CHAT_CREATE_GROUP_START",
  CHAT_CREATE_GROUP_SUCCESS: "CHAT_CREATE_GROUP_SUCCESS",
  CHAT_CREATE_GROUP_ERROR: "CHAT_CREATE_GROUP_ERROR",
  SOCKET_TYPING_ON: "SOCKET_TYPING_ON",
  SOCKET_TYPING_OFF: "SOCKET_TYPING_OFF",
  ON_CREATE_GROUP_SUCCESS: "ON_CREATE_GROUP_SUCCESS",

  INPUT_MESSAGE_CHANGE: "INPUT_MESSAGE_CHANGE",
  INPUT_IMAGE_LIST_CHANGE: "INPUT_IMAGE_LIST_CHANGE",
  INPUT_FILE_LIST_CHANGE: "INPUT_FILE_LIST_CHANGE",

  CHAT_GET_IMAGE_LIST_START: "CHAT_GET_IMAGE_LIST_START",
  CHAT_GET_IMAGE_LIST_SUCCESS: "CHAT_GET_IMAGE_LIST_SUCCESS",
  CHAT_GET_IMAGE_LIST_ERROR: "CHAT_GET_IMAGE_LIST_ERROR",

  CHAT_GET_FILE_LIST_START: "CHAT_GET_FILE_LIST_START",
  CHAT_GET_FILE_LIST_SUCCESS: "CHAT_GET_FILE_LIST_SUCCESS",
  CHAT_GET_FILE_LIST_ERROR: "CHAT_GET_FILE_LIST_ERROR",

  CHAT_GROUP_UPDATE_SUCCESS: "CHAT_GROUP_UPDATE_SUCCESS",
  CHAT_GROUP_REMOVE_MEMBER_SUCCESS: "CHAT_GROUP_REMOVE_MEMBER_SUCCESS",
  CHAT_GROUP_ADD_MEMBERS_SUCCESS: "CHAT_GROUP_ADD_MEMBERS_SUCCESS",
  CHAT_GROUP_CHANGE_AVATAR: "CHAT_GROUP_CHANGE_AVATAR",
  CHAT_GROUP_LEAVE: "CHAT_GROUP_LEAVE",
  GROUP_CHANGE_AVATAR: "GROUP_CHANGE_AVATAR",

  READ_MORE_START: "READ_MORE_START",
  READ_MORE_SUCCESS: "READ_MORE_SUCCESS",
  READ_MORE_ERROR: "READ_MORE_ERROR",

  CHAT_GROUP_KICK: "CHAT_GROUP_KICK",
  ON_ADDED_TO_GROUP: "ON_ADDED_TO_GROUP",
  ON_CHANGE_NAME_GROUP: "ON_CHANGE_NAME_GROUP",
  TARGET_UPDATE_USER: "TARGET_UPDATE_USER",

  ON_DISCONNECT: "ON_DISCONNECT",
};
